name: PvPRounds
version: 3.0.8
author: Rafael Auler
main: me.rafaelauler.Main
description: PvPRounds plugin
depend: [Vault]
softdepend: [ItemJoin, PlaceholderAPI]

commands:
   pvprounds:
   pvr:
   pvprounds2:
   pvr2:
   setrounds:
   setrounds2:
   
   
   